services:
  backend:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
      target: dev
    container_name: momentum-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./src:/app/apps/api/src
      - ./package.json:/app/apps/api/package.json
      - ./tsconfig.json:/app/apps/api/tsconfig.json
    networks:
      - momentum-network

networks:
  momentum-network:
    driver: bridge
